# Generated by Django 3.2.3 on 2022-01-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220113_0314'),
        ('store', '0015_customer_user'),
    ]

    operations = [
    ]
