# Generated by Django 3.2.3 on 2022-01-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_0002_auto_20220113_0314_0015_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='status',
        ),
    ]
