# Generated by Django 3.2.3 on 2022-01-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_complete_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
