# Generated by Django 3.2.3 on 2022-01-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
