# Generated by Django 3.2.3 on 2022-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='express_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
